### ISSUE TITLE
LaTeX tabular environments

### ISSUE THREAD

**Issue by mitchkeller** [davidfarmer/applied-combinatorics#2]
Tabular environments (some legitimate tables, others things  that aren't semantically tables and maybe should be something else) are not being converted properly to tables in MBX (coming out with a single column per row), and thus the HTML and LaTeX output is garbage. (The LaTeX output for these MBX tables isn't even giving me a tabular environment.)

**Comment by mitchkeller** [comment]
Sounds like once sl2x has proper code to take LaTeX tabular environments and output meaningfully to MBX like it does to HTML, this will be resolved.

**Comment by davidfarmer** [comment]
Should be okay, or at least better, in the recent pull request.

**Comment by mitchkeller** [comment]
These seem to be coming through fine now. The weird thing is that I took something that probably shouldn't be a table (It appears in both introduction.tex and genfunction.tex, if you want to see what I'm talking about.) and converted it to a multicols environment, which got processed really weirdly in the `xsltproc` conversions to LaTeX and HTML. The data gets moved from my LaTeX into the MBX, but then nothing but blank lines are sent out to LaTeX and HTML when the XSL is applied. This is easily fixed by reverting to a LaTeX tabular environment for sl2x to turn into an MBX table. I can then decide if there's a better way to present it.
