### ISSUE TITLE
\includegraphics scaling

### ISSUE THREAD

**Issue by mitchkeller** [davidfarmer/applied-combinatorics#4]
The round trip from LaTeX to LaTeX via MBX is producing (unsurprisingly) some pretty awful figure scaling problems (all our scaling instructions are being lost). Can we capture that scale data and use it in the process of making SVGs from the PDF figure files so that the SVGs are saved at the "right" scale for direct inclusion into the LaTeX?

**Comment by davidfarmer** [comment]
In you source I see the following scaling for includegraphics:

[height=1in]
[height=2 in, width=2 in]
[width=2in]
[scale=.5]

Obviously all those work in your original LaTeX, or else you wouldn't have use them.

But in the long run it would be good to have a uniform way to describe the scale.

Do you have a suggestion for how I should convert those to MBX? I think it is best if
I convert to a uniform markup, even if I fail to give the right numbers in some cases.

Or if it is a fact that different methods must be used in different circumstances, then
we just need to accept that and decide what are the reasonable options.

**Comment by davidfarmer** [comment]
Correction: you only have scale and width (not height), but you do have 
angle=90

So the question is simpler: is it a good idea or a bad idea to always use the same
size directive, or is it better (or necessary) to sometimes use an absolute size,
and other times use a relative scale?

**Comment by mitchkeller** [comment]
I can't think of any reason why I need both absolute and relative scaling. It looks like there are only a few that use absolute scaling, so I'm thinking that I could just go through and fix those up with a comparable relative scaling factor this afternoon. The angle=90 thing can be dealt with manually since it looks to have been used sparingly.

I need to go through and crop the images where we're still using a viewport, too. (I can only think of one instance where the viewport thing was used for a reason other than the image wasn't cropped properly, and that should be converted into multiple image files anyway.)

If that sounds reasonable, I'll go through and make some updates to the source and let you know here when my revisions are ready for you to pull later today or tomorrow.

**Comment by davidfarmer** [comment]
It would be great if the source code did not include any viewport
directives.

When you have new LaTeX source, I'll pull and then see if the MBX
conversion is better.

**Comment by mitchkeller** [comment]
What’s the best scaling convention to use in terms of making something useful for both HTML and LaTeX? It seems that when we were originally working on the book, most of the time (minus the ones I’m fixing now) we used scale=. Presently, likely influenced by making lots of beamer slides for classes, my usual practice in other documents is something like width=0.7\linewidth (where 0.7 is whatever seems appropriate). I can convert the fixed-dimension things to scale= for consistency with what else is there right now, or I could convert them to things in terms of \linewidth or \textwidth or something like that (since that seems like a more sensible approach than doing things always in terms of the original image size).

On May 19, 2016, at 11:22 AM, davidfarmer <notifications@github.com<mailto:notifications@github.com>> wrote:


It would be great if the source code did not include any viewport
directives.

When you have new LaTeX source, I'll pull and then see if the MBX
conversion is better.

On Thu, 19 May 2016, Mitchel T. Keller wrote:

>
> I can't think of any reason why I need both absolute and relative scaling. It looks like there are
> only a few that use absolute scaling, so I'm thinking that I could just go through and fix those up
> with a comparable relative scaling factor this afternoon. The angle=90 thing can be dealt with
> manually since it looks to have been used sparingly.
>
> I need to go through and crop the images where we're still using a viewport, too. (I can only think
> of one instance where the viewport thing was used for a reason other than the image wasn't cropped
> properly, and that should be converted into multiple image files anyway.)
>
> If that sounds reasonable, I'll go through and make some updates to the source and let you know here
> when my revisions are ready for you to pull later today or tomorrow.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on
> GitHub[AAM6LF5_SKNFpjC3Ah01_qC0toKut5diks5qDHSPgaJpZM4IQjCz.gif]
>
>
>

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/davidfarmer/applied-combinatorics/issues/4#issuecomment-220358712>

--
Mitch Keller
Assistant Professor of Mathematics
Washington & Lee University, Lexington VA
206 Robinson Hall ~ 540.458.8099 ~ http://www.rellek.net

**Comment by davidfarmer** [comment]
Would you be willing to ask the mathbook google group?  It would be good
to hear what other people are doing and hear other opinions, instead of
us trying to invent this ourselves.

**Comment by mitchkeller** [comment]
Done. I’ll work on eradicating the viewport option while awaiting some further guidance from the community on this.

> On May 20, 2016, at 8:01 AM, davidfarmer <notifications@github.com> wrote:
> 
> 
> Would you be willing to ask the mathbook google group? It would be good
> to hear what other people are doing and hear other opinions, instead of
> us trying to invent this ourselves.
> 
> 
> On Fri, 20 May 2016, Mitchel T. Keller wrote:
> 
> > What’s the best scaling convention to use in terms of making something useful for both HTML and
> > LaTeX? It seems that when we were originally working on the book, most of the time (minus the ones
> > I’m fixing now) we used scale=. Presently, likely influenced by making lots of beamer slides for
> > classes, my usual practice in other documents is something like width=0.7\linewidth (where 0.7 is
> > whatever seems appropriate). I can convert the fixed-dimension things to scale= for consistency with
> > what else is there right now, or I could convert them to things in terms of \linewidth or \textwidth
> > or something like that (since that seems like a more sensible approach than doing things always in
> > terms of the original image size).
> > 
> > On May 19, 2016, at 11:22 AM, davidfarmer <notifications@github.com<mailto:notifications@github.com>>
> > wrote:
> > 
> > 
> > It would be great if the source code did not include any viewport
> > directives.
> > 
> > When you have new LaTeX source, I'll pull and then see if the MBX
> > conversion is better.
> > 
> > On Thu, 19 May 2016, Mitchel T. Keller wrote:
> > 
> > >
> > > I can't think of any reason why I need both absolute and relative scaling. It looks like there are
> > > only a few that use absolute scaling, so I'm thinking that I could just go through and fix those up
> > > with a comparable relative scaling factor this afternoon. The angle=90 thing can be dealt with
> > > manually since it looks to have been used sparingly.
> > >
> > > I need to go through and crop the images where we're still using a viewport, too. (I can only think
> > > of one instance where the viewport thing was used for a reason other than the image wasn't cropped
> > > properly, and that should be converted into multiple image files anyway.)
> > >
> > > If that sounds reasonable, I'll go through and make some updates to the source and let you know
> > here
> > > when my revisions are ready for you to pull later today or tomorrow.
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on
> > > GitHub[AAM6LF5_SKNFpjC3Ah01_qC0toKut5diks5qDHSPgaJpZM4IQjCz.gif]
> > >
> > >
> > >
> > 
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly or view it on
> > GitHub<https://github.com/davidfarmer/applied-combinatorics/issues/4#issuecomment-220358712>
> > 
> > --
> > Mitch Keller
> > Assistant Professor of Mathematics
> > Washington & Lee University, Lexington VA
> > 206 Robinson Hall ~ 540.458.8099 ~ http://www.rellek.net
> > 
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on
> > GitHub[AAM6LEaK7LMnCyhdjwuXhvHAJEfA_guWks5qDZ6mgaJpZM4IQjCz.gif]
> > 
> > 
> >
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> 

-- 
Mitch Keller
Assistant Professor of Mathematics
Washington & Lee University, Lexington VA
206 Robinson Hall ~ 540.458.8099 ~ http://www.rellek.net

**Comment by davidfarmer** [comment]
If the latest pull request doesn't fix this, please start a new issue.

**Comment by mitchkeller** [comment]
As we discussed, there's going to be some manual processing to get things looking nice in both versions, but I'm content with this producing something that can be compiled without any bug fixing at this stage.
