### ISSUE TITLE
-, --, and --- in LaTeX

### ISSUE THREAD

**Issue by mitchkeller** [davidfarmer/applied-combinatorics#5]
Seems like dashes, endashes and emdashes are being mangled in the translation to MBX.

**Comment by davidfarmer** [comment]
Not sure what I am supposed to do with a single dash, but double and triple should be
converted properly in the next pull request.

**Comment by mitchkeller** [comment]
I'm not sure why I put a regular hyphen in the list here, but I'm quite happy with the results for -- and --- now.
