### ISSUE TITLE
Wrap overpic in image and latex-image-code

### ISSUE THREAD

**Issue by mitchkeller** [davidfarmer/applied-combinatorics#6]
With modifications to the mbx script (available on the dev branch of my fork of mathbook), I've managed to get overpic working. However, the export from LaTeX to MBX needs to be improved a bit to wrap the LaTeX code in the correct XML. As an example of what I got to work, see the following:

```xml
<image xml:id="img-fig_graphs_utils">
    <latex-image-code><![CDATA[
        \begin{overpic}{images/k33}
        \put(-37,92){ Water}
        \put(-66,50){ Electricity}
        \put(-76,5){ Natural gas}
        \put(90,92){ Home 1}
        \put(90,50){ Home 2}
        \put(90,5){ Home 3}
        \end{overpic}]]>
    </latex-image-code>
</image>
```

(That can be found in section7-5.mbx on the tweak-mbx branch of my applied-combinatorics repository.)

**Comment by mitchkeller** [comment]
I see that dealing with overpic was flagged for me to do manually in the issue on my repository. I can do that if need be, but it seems like doing something like I've suggested here should be possible with sl2x. I guess unless you're not wrapping tikz environments in `<latex-image-code>` either, in which case this is definitely something I'll need to tackle.

**Comment by davidfarmer** [comment]
Currently I see things like this:

  <figure xml:id="fig_graphs_isomorphic_ex" >
<caption>Are these graphs isomorphic?</caption>
\begin{overpic}[scale=0.6]{graphs-figs/isomorphic_ex}
      \put(22,47){<m>\bfG_1</m>}
      \put(74,47){<m>\bfG_2</m>}

(from section7-9.mbx)

It looks like all I need to do is put
<![CDATA[
before the \begin{overpic}
and 
]]>
after the \end{overpic}

That is easy for me to add, but please tell me if I am missing something.

**Comment by mitchkeller** [comment]
If you could put  
<image><latex-image-code><![CDATA[ 
before the \begin{overpic} and 
]]></latex-image-code></image> 
after the \end{overpic}, that would be great. Because of how these are used, I'll need to figure out the labels/xml:ids manually, I think, but this would save me a lot of rather robotic work since I'll need those pieces in every single place.

**Comment by mitchkeller** [comment]
Grr, I just realized (because I posted this during the great github database glitch), that some of my tags didn't make it through in my previous comment.

What would be ideal is
`<image><latex-image-code><![CDATA[` 
before the \begin{overpic} and 
`]]></latex-image-code></image> `
after the \end{overpic}.

**Comment by davidfarmer** [comment]
Let me try to fix this and also the other things you mentioned.

I'll report back, and maybe we talk tomorrow instead of today.

**Comment by davidfarmer** [comment]
Are all the mrow's broken or just some?  Can you tell me a couple
of specific examples?  I already have code that is supposed to fix that.

**Comment by mitchkeller** [comment]
All of them. `grep ‘</mrow>’` on the .mbx files just returns a bunch of lines containing nothing but an initial segment of whitespace and then `</mrow>`. For example, 
```
<md>
  <mrow>  a \amp =  45095080578985454453\quad\text{and}
      </mrow>
  <mrow>  b \amp =  115756986668303657898962467957.
      </mrow>
</md>
```
in s_intro_number.mbx. LaTeX is OK with the new line anywhere except the last `<mrow>` of an `<md>`, since it doesn't like a blank line before `\end{align*}`.

**Comment by mitchkeller** [comment]
Actually, let me not make a new issue like I promised in closing your PR, since it's still on topic here. The `latex-image-code` block gets passed off to the `mbx` script for processing, and thus we don't want `<m>` tags inside there. If you can avoid converting the $'s to `m` tags inside these `latex-image-code` elements, then I think we'll be good to go. (It's easy to get the full LaTeX file that comes out to `xsltproc` to compile by doing a global find and replace to get rid of those tags, but the `mbx` script is going to barf.)

**Comment by davidfarmer** [comment]
I updated the pull request.

I used \( and \) instead of $ and $.  Is that okay?

**Comment by mitchkeller** [comment]
Yes, that worked out fine. (I still haven't run things through the mbx script, but the LaTeX version compiles fine, so I'm confident that I can get my hacked version of the mbx script that will soon be submitted to Rob will work on these overpic blocks.)
