### ISSUE TITLE
Blank lines in <me> when converting LaTeX to MBX

### ISSUE THREAD

**Issue by mitchkeller** [davidfarmer/applied-combinatorics#7]
A lot of my files (starting with introduction.tex) have some equations that are of the form

```latex
 \[
blah
\]
```

The MBX output has blank lines inside `<me>`, which then result in the LaTeX you get from running `xsltproc` on the MBX not compiling. I'm hoping that `sl2x` can be modified to not keep the spurious newlines, especially since it seems that sometimes `\]` is preceded by spaces, so doing some sort of regex replacement across all the files is likely still going to leave some problem spots to clean up.

**Comment by davidfarmer** [comment]
Cleaning up entraneous blank lines will be automatic.  It is a relatively
simple thing to fix; I just haven't done it yet.

**Comment by davidfarmer** [comment]
Should be fixed now

**Comment by mitchkeller** [comment]
Agree that this is fixed. Closing.
